dist: trusty
sudo: false
language: cpp

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - boost1.67

script:
  - sh ./test-linux.sh
