dist: trusty
sudo: false
language: cpp

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - boost1.67
script:

  - cd ./src/cpp11/test/boost_test
  - mkdir travis-cmake-build
  - cd ./travis-cmake-build
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake ..
  - cd ..

  - cmake --build ./travis-cmake-build --target boost_test -- -j 4

  - "./travis-cmake-build/boost_test"
