dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - cd ./src/cpp11/test/boost_test
  - mkdir cmake-build-debug
  - cd ./cmake-build-debug
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ..
  - cd ..
  - cmake --build ./cmake-build-debug --target boost_test -- -j 4
