dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ./src/cpp11/test/boost_test
  - cmake ./src/cpp11/test/boost_test/cmake-build-debug --target boost_test -- -j 4
