dist: trusty
sudo: false
language: cpp

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - boost1.67

script:
# CPP11:
  - cd ./cpp11
# library:
  # configure cmake:
  - mkdir build
  - cd ./build && CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake ..
  - cd ..
  # build with cmake:
  - cmake --build ./build --target raffer_finally-static -- -j 4
  - cmake --build ./build --target raffer_finally-shared -- -j 4
  - cmake --build ./build --target raffer_system-static -- -j 4
  - cmake --build ./build --target raffer_system-shared -- -j 4

# tests:
  - cd ./test/boost
  # configure cmake:
  - mkdir build
  - cd ./build
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake ..
  - cd ..
  # build with cmake:
  - cmake --build ./build --target test_boost_raffer-static -- -j 4

  # run tests:
  - "./build/test_boost_raffer-static"
