PRIORITY  1 _ EQUALS \s*

PRIORITY  2 TYPE EQUALS PRIORITY(3)
PRIORITY  2 FUNC EQUALS PRIORITY(30)

PRIORITY  3 sign    EQUALS [-\+]
PRIORITY  3 number  EQUALS \d*\.?\d+
PRIORITY  3 String  EQUALS "([^"]*)"
PRIORITY  3 boolean EQUALS [01]

PRIORITY  6 system\s*String EQUALS std::basic::func::system

PRIORITY  7 pi|π EQUALS std::math::const::pi
PRIORITY  7 e    EQUALS std::math::const::e
PRIORITY  7 c    EQUALS std::phys::const::c

PRIORITY  7 true  EQUALS std::logic::const::true
PRIORITY  7 false EQUALS std::logic::const::false

PRIORITY  8 (sign)_(sign)        EQUALS std::math::func::rmsign
PRIORITY  8  \(_(sign?number)_\) EQUALS std::basic::func::arg1
PRIORITY  8 \[_(sign?number)_\]  EQUALS std::basic::func::arg1

PRIORITY  9 ⌊_(sign?number)_⌋    EQUALS std::math::func::floor
PRIORITY  9 ⌈_(sign?number)_⌉    EQUALS std::math::func::ceil

PRIORITY 13 (number)_\^_(sign?number)   EQUALS std::math::func::pow
PRIORITY 13 (number)_root_(sign?number) EQUALS std::math::func::root
PRIORITY 13 (number)_log_(sign?number)  EQUALS std::math::func::log
PRIORITY 14 (number)_\*_(sign?number)   EQUALS std::math::func::mult
PRIORITY 14 (number)_/_(sign?number)    EQUALS std::math::func::div
PRIORITY 14 (number)_mod_(sign?number)  EQUALS std::math::func::mod
PRIORITY 15 (sign?number)_\+_(number)   EQUALS std::math::func::add
PRIORITY 15 (sign?number)_-_(number)    EQUALS std::math::func::sub


PRIORITY 19 (?:¬|not)_(boolean)                 EQUALS std::logic::func::not
PRIORITY 20 (boolean)_(?:∧|and)_(boolean)       EQUALS std::logic::func::and
PRIORITY 20 (boolean)_(?:∨|or)_(boolean)        EQUALS std::logic::func::or
PRIORITY 20 (boolean)_(?:⊼|nand)_(boolean)      EQUALS std::logic::func::nand
PRIORITY 20 (boolean)_(?:⊽|nor)_(boolean)       EQUALS std::logic::func::nor
PRIORITY 21 (boolean)_(?:⇹|↮|⊻|⊕|xor)_(boolean) EQUALS std::logic::func::xor
PRIORITY 21 (boolean)_(?:↔|xnor)_(boolean)      EQUALS std::logic::func::xnor

PRIORITY 23 (?:∿|sin)_(number) EQUALS std::math::func::sin

PRIORITY 24 (number)\.\.+(number) EQUALS std::basic::func::range

PRIORITY 25 print_(number) EQUALS std::inout::func::print
PRIORITY 25 print_String   EQUALS std::inout::func::print

PRIORITY 24 String_<<_String EQUALS std::inout::func::fprint

PRIORITY 25 ² = ^2
PRIORITY 25 ³ = ^3

PRIORITY 25 ¼ EQUALS 1/4
PRIORITY 25 ½ EQUALS 1/2
PRIORITY 25 ¾ EQUALS 3/4
PRIORITY 25 ⅐ EQUALS 1/7
PRIORITY 25 ⅑ EQUALS 1/9
PRIORITY 25 ⅒ EQUALS 1/10
PRIORITY 25 ⅓ EQUALS 1/3
PRIORITY 25 ⅔ EQUALS 2/3
PRIORITY 25 ⅕ EQUALS 1/5
PRIORITY 25 ⅖ EQUALS 2/5
PRIORITY 25 ⅗ EQUALS 3/5
PRIORITY 25 ⅘ EQUALS 4/5
PRIORITY 25 ⅙ EQUALS 1/6
PRIORITY 25 ⅚ EQUALS 5/6
PRIORITY 25 ⅛ EQUALS 1/8
PRIORITY 25 ⅜ EQUALS 3/8
PRIORITY 25 ⅝ EQUALS 5/8
PRIORITY 25 ⅞ EQUALS 7/8
PRIORITY 25 ↉ EQUALS 0/3
