PRIORITY  3 boolean IS (?:0|1)

PRIORITY  7 true IS std::logic::const::true
PRIORITY  7 false IS std::logic::const::false

PRIORITY 19 (?:¬|not)_(boolean) IS std::logic::func::not
PRIORITY 20 (boolean)_(?:∧|and)_(boolean) IS std::logic::func::and
PRIORITY 20 (boolean)_(?:∨|or)_(boolean) IS std::logic::func::or
PRIORITY 20 (boolean)_(?:⊼|nand)_(boolean) IS std::logic::func::nand
PRIORITY 20 (boolean)_(?:⊽|nor)_(boolean) IS std::logic::func::nor
PRIORITY 21 (boolean)_(?:⇹|↮|⊻|⊕|xor)_(boolean) IS std::logic::func::xor
PRIORITY 21 (boolean)_(?:↔|xnor)_(boolean) IS std::logic::func::xnor

PRIORITY 23 (?:∿|sin)_(number) IS std::math::func::sin

PRIORITY 24 (number)\.\.+(number) IS std::basic::func::range