PRIORITY  3 sign IS [-\+]
PRIORITY  3 operator IS [\+-\*/]
PRIORITY  3 number IS \d*\.?\d+

PRIORITY  7 pi|π IS std::math::const::pi
PRIORITY  7 e IS std::math::const::e

//PRIORITY  7 (number)_(leftBracket|[[:alpha:]]) IS $1*$2

PRIORITY  8 (sign)_(sign) IS std::math::func::rmsign
PRIORITY  8 \(_(sign?number)_\) IS std::basic::func::arg1
PRIORITY  8 \[_(sign?number)_\] IS std::basic::func::arg1

PRIORITY  9 ⌊_(sign?number)_⌋ IS std::math::func::floor
PRIORITY  9 ⌈_(sign?number)_⌉ IS std::math::func::ceil

PRIORITY 13 (number)_\^_(sign?number) IS std::math::func::pow
PRIORITY 13 (number)_root_(sign?number) IS std::math::func::root
PRIORITY 13 (number)_log_(sign?number) IS std::math::func::log
PRIORITY 14 (number)_\*_(sign?number) IS std::math::func::mult
PRIORITY 14 (number)_/_(sign?number) IS std::math::func::div
PRIORITY 14 (number)_mod_(sign?number) IS std::math::func::mod
PRIORITY 15 (sign?number)_\+_(number) IS std::math::func::add
PRIORITY 15 (sign?number)_-_(number) IS std::math::func::sub


PRIORITY 25 ² IS ^2
PRIORITY 25 ³ IS ^3

PRIORITY 25 ¼ IS 1/4
PRIORITY 25 ½ IS 1/2
PRIORITY 25 ¾ IS 3/4
PRIORITY 25 ⅐ IS 1/7
PRIORITY 25 ⅑ IS 1/9
PRIORITY 25 ⅒ IS 1/10
PRIORITY 25 ⅓ IS 1/3
PRIORITY 25 ⅔ IS 2/3
PRIORITY 25 ⅕ IS 1/5
PRIORITY 25 ⅖ IS 2/5
PRIORITY 25 ⅗ IS 3/5
PRIORITY 25 ⅘ IS 4/5
PRIORITY 25 ⅙ IS 1/6
PRIORITY 25 ⅚ IS 5/6
PRIORITY 25 ⅛ IS 1/8
PRIORITY 25 ⅜ IS 3/8
PRIORITY 25 ⅝ IS 5/8
PRIORITY 25 ⅞ IS 7/8
PRIORITY 25 ↉ IS 0/3